### ISSUE TITLE
My input mode always in text mode

### ISSUE THREAD

**Issue by sghazall** [ggeop/Python-ai-assistant#124]
I try to speak with Jarvis, however nothing happen . Only when I type the instruction in text, jarvis do the tas
![jarvis](https://user-images.githubusercontent.com/95997474/152900560-a7ac363d-9c1a-4238-ac14-a2413c28db5e.png)
k

**Comment by ggeop** [comment]
Have you tried to change the input mode? By default is text. Write change settings, or simple "settings" as input and you can on the fly enable the voice commands

**Comment by sghazall** [comment]
Thank you for your response. Yeah, I tried change the input mode by editing Jarvis/src/jarvis/jarvis/setting.py before yet nothing happen.

But now its working using you guide. Thank you again!!
