### ISSUE TITLE
In setup.sh line 63

### ISSUE THREAD

**Issue by RAJAT-SOUL** [ggeop/Python-ai-assistant#76]
virtualenv command not found

**Comment by 11Tuvork28** [comment]
Check if it got installed via this command
 ```bash 
python3 -m pip show virtualenv
```

It should show you some info like the author but if it doesn't give anything out then you need to install it. Via 
```bash
python3 -m pip install virtualenv
```

**Comment by ggeop** [comment]
@RAJAT-SOUL are you still facing this issue? If yes can you provide the error log and the operation system which you are running it?

**Comment by t60001** [comment]
Hello, ggeop. I have the same problem.

Entered the command as described - 11Tuvork28 
It stopped there:
 System dependencies installation succeeded! 
Requirement already satisfied: virtualenv in /home/pc/.local/lib/python3.8/site-packages (20.0.31)
Requirement already satisfied: filelock<4,>=3.0.0 in /home/pc/.local/lib/python3.8/site-packages (from virtualenv) (3.0.12)
Requirement already satisfied: distlib<1,>=0.3.1 in /home/pc/.local/lib/python3.8/site-packages (from virtualenv) (0.3.1)
Requirement already satisfied: appdirs<2,>=1.4.3 in /home/pc/.local/lib/python3.8/site-packages (from virtualenv) (1.4.4)
Requirement already satisfied: six<2,>=1.9.0 in /usr/lib/python3/dist-packages (from virtualenv) (1.14.0)
 Install virtualenv succeeded! 
setup.sh: строка 63: virtualenv: команда не найдена
 Jarvis virtual env creation failed 

OS and parameters:
Ubuntu 20.04.1
Python 2.7.18rc1
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

**Comment by 11Tuvork28** [comment]
Yeah get the same error on ubuntu 20.04 based distros. So I suggest sticking to the recommended ubuntu version stated in the readme.

**Comment by t60001** [comment]
@11Tuvork28 
Understood, thank you, I'll try on 18.04 . Then accomplish your goal

**Comment by t60001** [comment]
@11Tuvork28 
Problem not solved = ( Installed 18.04 . 1 in 1 error

**Comment by 11Tuvork28** [comment]
Okay, thats weird then idk maybe @ggeop  has an idea.

**Comment by ggeop** [comment]
Hi @t60001, @11Tuvork28  has right this error is related with the Linux distribution. In  a new Linux VM with 18.04 it works fine, I have tested many times and also job in Travis is successful. 

Are you using Docker or virtual machine (VMWare or Virtual Box) and you have the same error with Ubuntu 20.04?

**Comment by 11Tuvork28** [comment]
Hi @ggeop, I caught my error :D was using a terminal with an active conda env so thats the error on my side. Deactivating the environment fixes the issue for me, I'm running a non vm system (Ubuntu 20.04 based distro). But I run into a problem with scipy installation but this most likely related to my distro or the setup of python.

**Comment by t60001** [comment]
Hi @ggeop . I use a virtual machine Virtual Box, tried to put on 18.04 and 20.04. On a clean ubuntu, before the installer, install PIP3 and bash. I think it makes sense to add this to the installation description. But then the error =(

**Comment by t60001** [comment]
@ggeop any ideas?

**Comment by ggeop** [comment]
Hi @t60001, why you installed PIP3 and bash? In a clean Ubuntu (16.04 or 18.04) you have to only run the setup.sh.
What error are you facing ( "But then the error =(" ) ?

**Comment by t60001** [comment]
@ggeop 
So:
1. Downloaded ubuntu 18.04.5-desktop-amd64 from the official website.
2. on VirtualBox installed Ubuntu 18.04.5-desktop-for AMD64 architecture
3. Immediately after starting, I go to the terminal and write the command: git clone https://github.com/ggeop/Jarvis.git
4. Writes: 'git' not found, but can be installed using: sudo apt install git
5. Enter the command: sudo apt install git and everything is fine.
6. again prescribe the command: git clone https://github.com/ggeop/Jarvis.git and it runs successfully. A Jarvis folder is created on the computer.
7. I Write the command: cd /home/ubnt/Jarvis
8. I Write the command: bash setup.sh
9. on the fifth confirmation time (y), the same error occurs as always.

P. s. Specially tried to put the English version of Ubuntu, tried to update and not to update it. I don't know what to do. Try installing it on a virtual machine like me. It can't be that the same error didn't come out.

**Comment by RAJAT-SOUL** [comment]
sorry for the late response but I was able to resolve it. I  don't remember the exact procedure How I did but it was something related to environment variables that I changed .

**Comment by t60001** [comment]
@RAJAT-SOUL Good afternoon. Thanks for the answer. But I didn't understand anything. What should I change and where? I haven't been able to install it for weeks =(

**Comment by 11Tuvork28** [comment]
Hm maybe dockerinzing the application would be best as this would prevent such errors, I'm looking forward to get working dockerfile done in the next days.

**Comment by t60001** [comment]
looking forward to. Thanks

**Comment by t60001** [comment]
Hi, everybody. The problem has not been solved. Am I the only one who can't get Jarvis started?
