### ISSUE TITLE
The virtualenv command is not working

### ISSUE THREAD

**Issue by Thirupathy123** [ggeop/Python-ai-assistant#77]
usage: virtualenv [--version] [--with-traceback] [-v | -q] [--discovery {builtin}] [-p py] [--creator {builtin,cpython3-posix,venv}] [--seeder {app-data,pip}] [--no-seed] [--activators comma_separated_list] [--clear]
                  [--system-site-packages] [--symlinks | --copies] [--download | --no-download] [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip] [--no-setuptools] [--no-wheel]
                  [--clear-app-data] [--symlink-app-data] [--prompt prompt] [-h]
                  dest
virtualenv: error: unrecognized arguments: attemept/jarvis jarvis_virtual
 Jarvis virtual env creation failed

**Comment by ggeop** [comment]
Hi @Thirupathy123! Where do you have this issue, in installation process, is it when you  run the setup.sh?
What operation system are you using?

**Comment by Thirupathy123** [comment]
Hey great work with the project i run this on vmware with a ubuntu v19.10 and this occurs when i run setup.sh and i tried changing the path info and the virtualenv works fine when i create it in the terminal and i can work on it too i tried running the setup for the previous version too but it shows the same error.

**Comment by Thirupathy123** [comment]
"attemept/jarvis jarvis_virtual": is the path for the folder in which the virtual environment is supposed to be created in

**Comment by ggeop** [comment]
Thanks for your interest!! Can you try to install it in Ubuntu 16.04? I don't have test is in 19.10, and I assume that this is the issue root. If you still have the error I will investigate it further.

**Comment by Thirupathy123** [comment]
sure i will do it right away actually it worked in 16.04 I'll try find what's wrong by looking at the major changes from then hope we can make this work really excited at the possibilities in this project

**Comment by ggeop** [comment]
Perfect! I close the ticket because it worked in Ubuntu 16.04, which is the suggested OS :-) . 
I hope in the future it will support 19.10
