### ISSUE TITLE
issue in  mongod.service:

### ISSUE THREAD

**Issue by AJANILOY** [ggeop/Python-ai-assistant#91]
Failed to start mongod.service: Unit mongod.service not found.
run_jarvis.sh: line 10: ./jarvis_virtualenv/bin/python: No such file or directory
Failed to stop mongod.service: Unit mongod.service not loaded.
why this happens, i tried another issue that has been fixed, but still
i am on kali linux

**Comment by ggeop** [comment]
Hi AJANILOY! The above issue fixed with commit c6629a27b39cfcaa9349914e3663e7b7f448dbea. 

Thanks for your time and your patience!

**Comment by ggeop** [comment]
c6629a27b39cfcaa9349914e3663e7b7f448dbea
